-- Move 18 shows into the anime library bucket.
-- Generated by scripts/anime-migration-sql.mjs from anime-list.txt.
--
-- BEFORE RUNNING:
--   1. Back up the Floppy database.
--   2. Stop the Floppy container.
--   3. Set Preferences -> anime_library_mode to "both", or grouped anime will
--      appear in NEITHER the TV list nor the Anime list. This is verified
--      behaviour, not a guess.
--
-- Works on SQLite and PostgreSQL as written.

BEGIN;

-- 1. PRE-FLIGHT: must return 0 rows. Any row here is an existing anime-bucket
--    item that would collide with the update, since every app_item uniqueness
--    constraint includes library_media_type.
SELECT source, media_id, media_type, season_number, episode_number
FROM app_item
WHERE library_media_type = 'anime'
  AND (source, media_id) IN (
    ('tmdb', '43167'),
    ('tmdb', '70881'),
    ('tmdb', '62745'),
    ('tmdb', '95479'),
    ('tmdb', '280110'),
    ('tmdb', '46260'),
    ('tmdb', '31910'),
    ('tmdb', '65942'),
    ('tmdb', '69292'),
    ('tmdb', '205050'),
    ('tmdb', '127532'),
    ('tmdb', '229676'),
    ('tmdb', '120089'),
    ('tmdb', '78204'),
    ('tmdb', '82684'),
    ('tmdb', '62104'),
    ('tmdb', '218843'),
    ('tmdb', '118541')
  );

-- 2. BEFORE: record what is about to change.
SELECT library_media_type, media_type, COUNT(*) AS rows
FROM app_item
WHERE (source, media_id) IN (
    ('tmdb', '43167'),
    ('tmdb', '70881'),
    ('tmdb', '62745'),
    ('tmdb', '95479'),
    ('tmdb', '280110'),
    ('tmdb', '46260'),
    ('tmdb', '31910'),
    ('tmdb', '65942'),
    ('tmdb', '69292'),
    ('tmdb', '205050'),
    ('tmdb', '127532'),
    ('tmdb', '229676'),
    ('tmdb', '120089'),
    ('tmdb', '78204'),
    ('tmdb', '82684'),
    ('tmdb', '62104'),
    ('tmdb', '218843'),
    ('tmdb', '118541')
  )
GROUP BY library_media_type, media_type
ORDER BY media_type;

-- 3. THE CHANGE. Covers the show plus its season and episode rows, which share
--    (source, media_id).
UPDATE app_item
SET library_media_type = 'anime'
WHERE (source, media_id) IN (
    ('tmdb', '43167'),
    ('tmdb', '70881'),
    ('tmdb', '62745'),
    ('tmdb', '95479'),
    ('tmdb', '280110'),
    ('tmdb', '46260'),
    ('tmdb', '31910'),
    ('tmdb', '65942'),
    ('tmdb', '69292'),
    ('tmdb', '205050'),
    ('tmdb', '127532'),
    ('tmdb', '229676'),
    ('tmdb', '120089'),
    ('tmdb', '78204'),
    ('tmdb', '82684'),
    ('tmdb', '62104'),
    ('tmdb', '218843'),
    ('tmdb', '118541')
  );

-- 4. AFTER: every row above should now read 'anime'.
SELECT library_media_type, media_type, COUNT(*) AS rows
FROM app_item
WHERE (source, media_id) IN (
    ('tmdb', '43167'),
    ('tmdb', '70881'),
    ('tmdb', '62745'),
    ('tmdb', '95479'),
    ('tmdb', '280110'),
    ('tmdb', '46260'),
    ('tmdb', '31910'),
    ('tmdb', '65942'),
    ('tmdb', '69292'),
    ('tmdb', '205050'),
    ('tmdb', '127532'),
    ('tmdb', '229676'),
    ('tmdb', '120089'),
    ('tmdb', '78204'),
    ('tmdb', '82684'),
    ('tmdb', '62104'),
    ('tmdb', '218843'),
    ('tmdb', '118541')
  )
GROUP BY library_media_type, media_type
ORDER BY media_type;

-- 5. Nothing else should have moved. Expect 0.
SELECT COUNT(*) AS unexpected_anime_rows
FROM app_item
WHERE library_media_type = 'anime'
  AND (source, media_id) NOT IN (
    ('tmdb', '43167'),
    ('tmdb', '70881'),
    ('tmdb', '62745'),
    ('tmdb', '95479'),
    ('tmdb', '280110'),
    ('tmdb', '46260'),
    ('tmdb', '31910'),
    ('tmdb', '65942'),
    ('tmdb', '69292'),
    ('tmdb', '205050'),
    ('tmdb', '127532'),
    ('tmdb', '229676'),
    ('tmdb', '120089'),
    ('tmdb', '78204'),
    ('tmdb', '82684'),
    ('tmdb', '62104'),
    ('tmdb', '218843'),
    ('tmdb', '118541')
  );

-- Inspect the results above. COMMIT only if steps 1 and 5 returned 0 and step 4
-- looks right. Otherwise ROLLBACK.
-- COMMIT;
ROLLBACK;
